#!/system/xbin/bash

main_file=$(basename ${BASH_SOURCE[0]})

if [ ! -e $main_file ]
then
	clear
	echo
	echo "You must run this tool from working directory!"
	echo
	exit 1
fi

required_dirs=(
	"include/main"
	"include/game_scripts"
	"data"
)

for check_dir in ${required_dirs[@]}
do
	if [ ! -e $check_dir ]
	then
		clear
		echo "Error: folder not found '$check_dir'"
		error_found=1
	fi
done

working_dirs=(
	"logs"
	"tmp"
	"profiles"
)

for check_dir in ${working_dirs[@]}
do
	if [ ! -e $check_dir ]
	then
		mkdir -p $check_dir
		chmod 0700 $check_dir
	fi
done

if [ $error_found == 1 ]
then
	echo
	echo "Required files are missing!."
	exit 0
fi

clear

for check_dir in ${required_dirs[@]}
do
	chmod 0700 $required_dirs/*
done

source include/main/check_settings && check_settings
source .settings

if [ "$GAME_INSTALLED" == "0" ]
then
	echo
	echo "Please, install game first!"
	echo
	rm .settings
	exit
fi

source $INCLUDE_DIR/main/get_func
get_func "$INCLUDE_DIR/main"

"$@"
