#!/system/xbin/bash

dir_list=( tools/test tools/scripts )
error_found=0

for check_dir in ${dir_list[@]}
do
	if [ ! -e $check_dir ]
	then
		clear
		echo "Error: folder not found '$check_dir'"
		error_found=1
	fi
done

if [ ! -e profiles ]
then
	mkdir profiles
	chmod 0700 profiles
fi

if [ ! -e logs ]
then
	mkdir logs
	chmod 0700 logs
fi

if [ ! -e tmp ]
then
	mkdir tmp
	chmod 0700 tmp
fi

if [ $error_found == 1 ]
then
	echo
	echo "Required files are missing!."
	exit 0
fi

clear

chmod 0700 tools/scripts/*
chmod 0700 tools/test/*
chmod 0700 tools/completion/*



source tools/scripts/get_functions && get_functions && check_settings

source .settings

if [ "$GAME_INSTALLED" == "0" ]
then
	echo
	echo "Please, install game first!"
	echo
	rm .settings
	exit
fi

ROOTU=$(isroot)

if [ $ROOTU == 0 ]
then
	echo "Root permissions required"
	echo
	exit 0
fi

trap 'del_tmp' EXIT # calls deletetempfiles function on exit

source `pwd`/.variables

"$@"
